name: Base Setup

on:
  workflow_call:
    inputs:
      python-version:
        description: 'The Python version to use'
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set up Docker Compose on Windows
        if: runner.os == 'Windows'
        run: |
          echo "Setting up Docker Compose on Windows..."
          curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-windows-x86_64.exe" -o /usr/local/bin/docker-compose.exe
          chmod +x /usr/local/bin/docker-compose.exe
        shell: bash

      - name: Set up Docker Compose on macOS
        if: runner.os == 'macOS'
        run: |
          echo "Setting up Docker Compose on macOS..."
          brew install docker-compose
        shell: bash

      - name: Check Docker and Docker Compose
        run: |
          echo "Checking Docker and Docker Compose versions..."
          docker --version
          docker compose version
        shell: bash

