name: RabbitMQ Tests

on:
  push:
    branches:
      - main
    paths:
        - 'connectiva/protocols/amqp_protocol.py'
        - 'tests/test_amqp_protocol.py'
        - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
        - 'connectiva/protocols/amqp_protocol.py'
        - 'tests/test_amqp_protocol.py'
        - 'pyproject.toml'

jobs:
  test-rabbitmq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Add Poetry to Path
        run: echo "export PATH=\"$HOME/.local/bin:\$PATH\"" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install

      - name: Start RabbitMQ Service
        run: |
          echo "Starting RabbitMQ service on Python ${{ matrix.python-version }}..."
          docker compose -f docker/docker-compose.rabbitmq.yml up -d

      - name: Run RabbitMQ Tests
        run: |
          echo "Running RabbitMQ tests on Python ${{ matrix.python-version }}..."
          poetry run python -m unittest discover -s tests -p 'test_amqp_protocol.py'

      - name: Stop RabbitMQ Service
        run: |
          echo "Stopping RabbitMQ service..."
          docker compose -f docker/docker-compose.rabbitmq.yml down
