name: RabbitMQ Tests

on:
  push:
    branches:
      - main
    paths:
      - 'connectiva/protocols/amqp_protocol.py'
      - 'tests/test_amqp_protocol.py'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'connectiva/protocols/amqp_protocol.py'
      - 'tests/test_amqp_protocol.py'
      - 'pyproject.toml'

jobs:
  base-setup:
    uses: ./.github/workflows/base.yml
    with:
      python-version: ${{ matrix.python-version }}

  test-rabbitmq:
    needs: base-setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start RabbitMQ Service
        run: |
          echo "Starting RabbitMQ service on Python ${{ matrix.python-version }}..."
          docker compose -f docker/docker-compose.rabbitmq.yml up -d
        shell: bash

      - name: Run RabbitMQ Tests
        run: |
          echo "Running RabbitMQ tests on Python ${{ matrix.python-version }}..."
          poetry run python -m unittest discover -s tests -p 'test_amqp_protocol.py'
        shell: bash

      - name: Stop RabbitMQ Service
        run: |
          echo "Stopping RabbitMQ service..."
          docker compose -f docker/docker-compose.rabbitmq.yml down
        shell: bash
